---
- name: Configure Nginx as Load Balancer
  hosts: lbr
  become: yes

  tasks:
    - name: Install nginx
      package:
        name: nginx
        state: present

    - name: Configure nginx.conf for load balancing with App server IPs
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user  nginx;
          worker_processes  auto;
          error_log  /var/log/nginx/error.log warn;
          pid        /var/run/nginx.pid;

          events {
              worker_connections  1024;
          }

          http {
              upstream app_servers {
                  server 172.16.238.10:6000;
                  server 172.16.238.11:6000;
                  server 172.16.238.12:6000;
              }

              server {
                  listen 80;

                  location / {
                      proxy_pass http://app_servers;
                      proxy_set_header Host $host;
                      proxy_set_header X-Real-IP $remote_addr;
                      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                      proxy_set_header X-Forwarded-Proto $scheme;
                  }
              }
          }


    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
